language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools # intentional, see travis-ci/docs-travis-ci-com#779
    - build-tools-28.0.3
    - android-22 # For emulator to work
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-15
    - sys-img-armeabi-v7a-android-22
  licenses:
    - android-sdk-license-.+
env:
  matrix:
    - ANDROID_SDKS=android-22,sysimg-22  ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
before_script:
  - chmod +x gradlew
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
after_failure:
  - cat $TRAVIS_BUILD_DIR/library/build/outputs/lint-results-debug.xml
  - cat $TRAVIS_BUILD_DIR/library/build/reports/androidTests/connected/index.html
